spring.jpa.hibernate.ddl-auto: validate
spring.datasource.url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/hot_news_db?serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: 27526976
spring.jpa.show-sql: false